function length(value, len) {
  if (value.trim().length > len) {
    return true;
  } else {
    return false;
  }
}

function validateEmail(email) {
  const regEx = /\S+@\S+\.\S+/;
  const patternMatches = regEx.test(email);
  return patternMatches;
}

const form = document.querySelector(".contactform");
const userName = document.querySelector("#name");
const nameError = document.querySelector("#name-error");
const subject = document.querySelector("#subject");
const subjectError = document.querySelector("#subject-error");
const email = document.querySelector("#email");
const emailError = document.querySelector("#email-error");
const message = document.querySelector("#message");
const messageError = document.querySelector("#message-error");

// Form validation
function validateForm(event) {
  event.preventDefault();

  let isValid = true;
  
  if (length(userName.value, 5) === true) {
    nameError.style.display = "none";
  } else {
    nameError.style.display = "block";
    isValid = false;
  }

  if (length(subject.value, 15) === true) {
    subjectError.style.display = "none";
  } else {
    subjectError.style.display = "block";
    isValid = false;
  }

  if (validateEmail(email.value) === true) {
    emailError.style.display = "none";
  } else {
    emailError.style.display = "block";
    isValid = false;
  }

  if (length(message.value, 25) === true) {
    messageError.style.display = "none";
  } else {
    messageError.style.display = "block";
    isValid = false;
  }

  if (isValid) {
    // If valid, post object to WordPress, can be fetched using custom endpoint: https://gamehub.olekristianfrontend.no/wp-json/myplugin/v1/formdata
    const formData = {
      name: userName.value,
      subject: subject.value,
      email: email.value,
      message: message.value,
    };

    fetch('https://gamehub.olekristianfrontend.no/wp-json/myplugin/v1/contact', { //custom endpoint generated by custom plugin
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(formData),
    })
    .then(response => {
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return response.json();
    })
    .then(data => console.log('Success:', data))
    .catch((error) => {
      console.error('Error:', error);
    });
  }
}

form.addEventListener("submit", validateForm);
